sendprivatemsg: 'send_private_msg'
sendgroupmsg: 'send_group_msg'
sendmsg: 'send_msg'
deletemsg: 'delete_msg'
setgroupkick: 'set_group_kick'
setgroupban: 'set_group_ban'
setgroupwholeban: 'set_group_whole_ban'
setgroupadmin: 'set_group_admin'
setgroupcard: 'set_group_card'
setgroupname: 'set_group_name'
setgroupleave: 'set_group_leave'
setgroupspecialtitle: 'set_group_special_title'
setfriendaddrequest: 'set_friend_add_request'
setgroupaddrequest: 'set_group_add_request'
getlogininfo: 'get_login_info'
getstrangerinfo: 'get_stranger_info'
getfriendlist: 'get_friend_list'
getgroupinfo: 'get_group_info'
getgrouplist: 'get_group_list'
getgroupmemberinfo: 'get_group_member_info'
getgroupmemberlist: 'get_group_member_list'
getgrouphonorinfo: 'get_group_honor_info'
cansendimage: 'can_send_image'
cansendrecord: 'can_send_record'
getversioninfo: 'get_version_info'
setrestart: 'set_restart'
sendgroupforwardmsg: 'send_group_forward_msg'
sendprivateforwardmsg: 'send_private_forward_msg'


