plugins:
  - name: test
    keyword: /早报
    args: ["订阅","退订"]
    whitelist: ["2292348488"]
    status: true
  - name: music
    keyword: /点歌
    args: []
    whitelist: ["1552899301"]
    status: true
  - name: magnet
    keyword: /资源
    args: []
    whitelist: []
    status: true
  - name: ali_search
    keyword: /云盘
    args: []
    whitelist: []
    status: true
  - name: gpt_summary
    keyword: /总结
    args: []
    whitelist: []
    status: true