plugins:
  - name: test
    keyword: /早报
    args: ["订阅","退订"]
    scope: []
    whitelist: ["2292348488"]
    status: true
  - name: music
    keyword: /点歌
    args: []
    scope: []
    whitelist: []
    status: true
  - name: magnet
    keyword: /资源
    args: []
    whitelist: []
    scope: []
    status: true
  - name: ali_search
    keyword: /云盘
    whitelist: []
    args: []
    scope: []
    status: true
  - name: happy
    keyword: /色图
    whitelist: []
    args: []
    scope: ["private"]
    status: true
  - name: gpt_summary
    keyword: /总结
    args: [ ]
    whitelist: [ ]
    scope: []
    status: true
