ws: 'ws://43.248.189.42:10170'
# magnet: 'https://doc.htmcdn.com:39988/search-%s-viewnum-1.html?'
magnet: 'https://www.cilidandan5.com/web-api/web/search/list?pageNum=1&pageSize=12&keyword=%s&order=all&date=0&sort=&category=video'
#magnet: 'https://lemonju.top/search?keyword=%s&sos=relevance&sofs=all&sot=all&soft=all&som=exact&p=1'
#magnet: 'https://cilisousuo.com/search?q=%s'
#ali: 'http://yiso.fun/api/search?name=%s&from=ali&pageNo=%d'
ali: 'https://upapi.juapp9.com/search?keyword=%s&page=1&s_type=2'
mysql: 'qq:123abc,.?@tcp(47.115.206.213:3306)/qqbot'
cloudsong: 'http://music.163.com/api/search/pc?s=%s&offset=0&limit=1&type=1'
reply: 'http://api.qingyunke.com/api.php?key=free&appid=0&msg=%s'
weather: 'https://v0.yiketianqi.com/api?unescape=1&version=v91&appid=43656176&appsecret=I42og6Lm&ext=&cityid=&city=%s'
joke: 'https://api.vvhan.com/api/joke'
hot: 'https://api.vvhan.com/api/sao'
love: 'https://api.vvhan.com/api/love'
taoshow: 'https://api.vvhan.com/api/tao?type=json'
cosshow: 'https://api.dzzui.com/api/cosplay?format=json'
moyu: 'https://api.j4u.ink/v1/store/other/proxy/remote/moyu.json'
book: 'https://www.htcomic.top/search/?q=%s&f=_all&s=create_time_DESC&syn=yes'
qqsong: 'http://ovooa.com/API/QQ_Music/?Skey=&uin=&msg=%s&n=1'
openaimessage: 'https://api.openai.com/v1/completions'
openaiphoto: 'https://api.openai.com/v1/images/generations'
verb: 'https://www.tbsdy.com/search.html?keyword=%s'